language: node_js
node_js:
- 'lts/*'
before_script:
- .github/patch-version.sh
cache: yarn
dist: xenial
# Push site to gh-pages branch
deploy:
  - provider: script
    skip_cleanup: true
    script: .github/deploy.sh
    on:
      branch: master
